version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/Users/emrecanortakci/IdeaProjects/volumes
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
volumes:
  db:
    driver: local